"""Pydantic data models for the RAKSHA security system."""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Optional

import numpy as np
from pydantic import BaseModel, Field


class Severity(str, Enum):
    """Alert severity levels."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"
    EMERGENCY = "emergency"


class AnomalyType(str, Enum):
    """Types of behavioral anomalies."""

    LOITERING = "loitering"
    RUNNING = "running"
    CROWD_FORMING = "crowd_forming"
    PERIMETER_BREACH = "perimeter_breach"


class ZoneType(str, Enum):
    """Types of monitored zones."""

    RESTRICTED = "restricted"
    MONITORED = "monitored"


class BoundingBox(BaseModel):
    """Axis-aligned bounding box."""

    x: float = Field(ge=0, description="Top-left x coordinate")
    y: float = Field(ge=0, description="Top-left y coordinate")
    width: float = Field(gt=0)
    height: float = Field(gt=0)

    @property
    def center(self) -> tuple[float, float]:
        return (self.x + self.width / 2, self.y + self.height / 2)

    @property
    def area(self) -> float:
        return self.width * self.height

    def iou(self, other: BoundingBox) -> float:
        """Compute intersection-over-union with another box."""
        x1 = max(self.x, other.x)
        y1 = max(self.y, other.y)
        x2 = min(self.x + self.width, other.x + other.width)
        y2 = min(self.y + self.height, other.y + other.height)
        intersection = max(0, x2 - x1) * max(0, y2 - y1)
        union = self.area + other.area - intersection
        return intersection / union if union > 0 else 0.0


class Frame(BaseModel):
    """A single video frame with metadata."""

    model_config = {"arbitrary_types_allowed": True}

    frame_id: int = Field(ge=0)
    timestamp: datetime = Field(default_factory=datetime.now)
    width: int = Field(gt=0, default=640)
    height: int = Field(gt=0, default=480)
    data: Optional[np.ndarray] = Field(default=None, exclude=True)

    @property
    def shape(self) -> tuple[int, int]:
        return (self.height, self.width)


class Detection(BaseModel):
    """A detected object in a frame."""

    detection_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    frame_id: int
    timestamp: datetime = Field(default_factory=datetime.now)
    bbox: BoundingBox
    label: str = "person"
    confidence: float = Field(ge=0.0, le=1.0)
    track_id: Optional[int] = None


class SecurityEvent(BaseModel):
    """A recorded security event."""

    event_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    timestamp: datetime = Field(default_factory=datetime.now)
    event_type: str
    anomaly_type: Optional[AnomalyType] = None
    severity: Severity = Severity.INFO
    zone_name: Optional[str] = None
    detections: list[Detection] = Field(default_factory=list)
    description: str = ""
    metadata: dict = Field(default_factory=dict)


class Alert(BaseModel):
    """An alert generated by the system."""

    alert_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    timestamp: datetime = Field(default_factory=datetime.now)
    severity: Severity
    title: str
    description: str
    event: Optional[SecurityEvent] = None
    acknowledged: bool = False
    notified: bool = False
